[build]
  base    = "website"
  publish = "website"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "https://coina.ge"
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"